// This file was generated by the protobuf compiler. Do not edit.
//==================================================

interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  isActive: boolean;
  createdAt: number;
  updatedAt: number;
}

interface CreateUserRequest {
  firstName: string;
  lastName: string;
  email: string;
}

interface UpdateUserRequest {
  id: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  isActive?: boolean;
}

interface UserResponse {
  user: User;
}

interface ListUsersResponse {
  users: User[];
  totalCount: number;
}

//==================================================