// This file was generated by the protobuf compiler. Do not edit.
//==================================================

package profile

type User struct {
	Id string `json:"id"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	Email string `json:"email"`
	IsActive bool `json:"isActive"`
	CreatedAt int64 `json:"createdAt"`
	UpdatedAt int64 `json:"updatedAt"`
}

type CreateUserRequest struct {
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	Email string `json:"email"`
}

type UpdateUserRequest struct {
	Id string `json:"id"`
	FirstName *string `json:"firstName,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	Email *string `json:"email,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
}

type UserResponse struct {
	User User `json:"user"`
}

type ListUsersResponse struct {
	Users []User `json:"users"`
	TotalCount int64 `json:"totalCount"`
}

//==================================================